[workspace]
members = [
  "sw",
  "svd2utra",
  "xtask",
]

exclude = [
  "utralib", # this is machine generated
]

[profile.release]
opt-level = 3
codegen-units = 1  # more optimization
debug = true
lto = "fat"
