[workspace]
members = [
  "sw",
  "svd2utra",
  "xtask",
]

exclude = [
  "utralib", # this is machine generated
]

[profile.release]
opt-level = "s"
codegen-units = 1  # more optimization
lto = "fat"
panic = "abort"
